#!/bin/bash

#need to add user to sudoers before running

cd ~

sudo apt update -qq
sudo apt upgrade
sudo apt-get dist-upgrade

sudo apt-get install sublime-text-installer
sudo apt-get install chromium
sudo apt-get install unrar
sudo apt-get install curl

#SublimeText
wget -qO - https://download.sublimetext.com/sublimehq-pub.gpg | sudo apt-key add -
sudo echo "deb https://download.sublimetext.com/ apt/stable/" > /etc/apt/sources.list.d/sublime-text.list
sudo apt install apt-transport-https
sudo apt update
sudo apt install sublime-text

#Papirus Icons
wget -qO- https://raw.githubusercontent.com/PapirusDevelopmentTeam/papirus-icon-theme/master/install.sh | sh
Gnome-tweak-tool

#Docker
sudo curl -sSL https://get.docker.com | sh
sudo usermod -aG docker james

#PIA
sudo apt-get install curl network-manager-openvpn-gnome

